### ISSUE TITLE
get_http_file: Multiple Files upload

### ISSUE THREAD

**Issue by DurgaAdd** [teamcgc/cgcR#5]
It would be useful to be able to upload multiple files from single or multiple links (like on GUI) and one metadata file for the whole set. This is getting interesting!

**Comment by seandavi** [comment]
The multiple files upload is handled easily by creating separate tasks for each file. In the API, that is easy to do.  The advantage of this approach over having the tool handle multiple files itself is that each instance of the tool will run in parallel.  If the tool does multiple files, they will run in series.  

We should look into "batch" to see if there is a way to launch the tool multiple times easily via the UI.

**Comment by DurgaAdd** [comment]
That was my next thought.
Thanks.
